name: CI

on:
  push:
    branches:
    - "**"
  pull_request:
  workflow_dispatch:

jobs:
  v2_23:
    runs-on: ubuntu-22.04
    name: glibc-v2.23
    steps:
      - name: build how2heap
        uses: Kyle-Kyle/action_test/ci/build@main
        with:
          ubuntu: '16.04'
      - name: test how2heap
        uses: Kyle-Kyle/action_test/ci/test@main
        with:
          ubuntu: '16.04'
          glibc: '2.23'
