name: CI

on:
  push:
    branches:
    - "**"
  pull_request:
  workflow_dispatch:

jobs:
  v2_23:
    runs-on: ubuntu-20.04
    name: glibc-v2.23
    steps:
      - name: test how2heap on glibc-2.23
        uses: Kyle-Kyle/action_test/ci@main
