name: CI

on:
  push:
    branches:
    - "**"
  pull_request:
  workflow_dispatch:

jobs:
  v2_23:
    runs-on: ubuntu-22.04
    name: glibc-v2.23
    steps:
      - name: system prep
        run: |
          docker pull ubuntu:16.04
          docker tag ubuntu16.04 base
